snapshot: lts-22.22
packages: 
- opt-env-conf
- /home/syd/src/autodocodec/autodocodec
- /home/syd/src/autodocodec/autodocodec-schema/
- /home/syd/src/autodocodec/autodocodec-yaml/
- /home/syd/src/safe-coloured-text/safe-coloured-text
- /home/syd/src/safe-coloured-text/safe-coloured-text-layout

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
  # - github: NorfairKing/safe-coloured-text
  #   commit: 4161e707b1b0a8090a7149b8195f15943fa29fa9
  #   subdirs:
  #   - safe-coloured-text
  #   - safe-coloured-text-gen

system-ghc: true
nix:
  enable: false
with-hpack: hpack
