name: opt-env-conf-test
version: '0.0.0.0'
copyright: ! 'Copyright: (c) 2024 Tom Sydney Kerckhove'
license: AllRightsReserved
  
extra-source-files:
- test_resources/**/*

dependencies:
- base


library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - opt-env-conf
  - safe-coloured-text
  - sydtest
  - text

tests:
  opt-env-conf-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson 
    - containers
    - envparse
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-sydtest
    - genvalidity-text
    - opt-env-conf
    - optparse-applicative
    - pretty-show
    - safe-coloured-text
    - safe-coloured-text-terminfo
    - sydtest
    - text
    - yaml
    - opt-env-conf-test
