name: opt-env-conf
version: '0.0.0.0'
copyright: ! 'Copyright: (c) 2024 Tom Sydney Kerckhove'
license: AllRightsReserved
  
extra-source-files:
- test_resources/**/*

dependencies:
- base


library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - containers
  - envparse
  - filepath
  - mtl
  - optparse-applicative
  - path
  - path-io
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo # TODO Don't depend on this on windows
  - selective
  - text
  - validity
  - validity-containers
  - yaml

tests:
  opt-env-conf-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson 
    - containers
    - envparse
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-sydtest
    - genvalidity-text
    - opt-env-conf
    - optparse-applicative
    - pretty-show
    - safe-coloured-text
    - sydtest
    - text
    - yaml
