name: opt-env-conf
version: '0.0.0.0'
copyright: ! 'Copyright: (c) 2024 Tom Sydney Kerckhove'
license: AllRightsReserved
  
extra-source-files:
- test_resources/**/*

dependencies:
- base


library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-schema
  - autodocodec-yaml
  - containers
  - filepath
  - mtl
  - path-io
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo # TODO Don't depend on this on windows
  - selective
  - text
  - validity
  - validity-containers
